### ISSUE TITLE
Build error. OpenWRT 15.05

### ISSUE THREAD

**Issue by h1aji** [netxms/openwrt-feed#2]
I am getting following error trying to compile:
`In file included from libnetxms.h:27:0,
                 from tools.cpp:23:
../../include/nms_common.h:1175:13: error: previous declaration of 'void nx_free(void*)' with 'C++' linkage
 inline void nx_free(void *p)
             ^
In file included from /root/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include/features.h:416:0,
                 from /root/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include/wchar.h:28,
                 from ../../include/unicode.h:121,
                 from ../../include/nms_common.h:72,
                 from libnetxms.h:27,
                 from tools.cpp:23:
/root/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include/malloc.h:119:18: error: conflicts with new declaration with 'C' linkage
 extern void free __MALLOC_P ((__malloc_ptr_t __ptr));
                  ^
make[6]: *** [libnetxms_la-tools.lo] Error 1
make[6]: Leaving directory`/root/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/netxms-agent-nossl/netxms-2.0.5/src/libnetxms'
make[5]: **\* [all-recursive] Error 1
make[5]: Leaving directory `/root/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/netxms-agent-nossl/netxms-2.0.5/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory`/root/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/netxms-agent-nossl/netxms-2.0.5'
make[3]: **\* [all] Error 2
make[3]: Leaving directory `/root/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/netxms-agent-nossl/netxms-2.0.5'
make[2]: *** [/root/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/netxms-agent-nossl/netxms-2.0.5/.built] Error 2
make[2]: Leaving directory`/root/openwrt/feeds/netxms/admin/netxms'
make[1]: **\* [package/feeds/netxms/netxms/install] Error 2
make[1]: Leaving directory `/root/openwrt'
make: *** [package/netxms/install] Error 2
`
Tried with 2.0.2 and 2.0.5. Same error

**Comment by 2128506** [comment]
Fixed.
